### ISSUE TITLE
return event type

### ISSUE THREAD

**Issue by guo-yong-zhi** [fonsp/PlutoImageCoordinatePicker.jl#8]
Could the event type be returned? Sometimes, we want to distinguish among mouseup, mousedown, pointer_move...

**Comment by fonsp** [comment]
Ah interesting! It's not an exact mirror of all web mouse events but the mouseup might be nice to distinguish.

Could you write a bit about how you are thinking of using this?

**Comment by guo-yong-zhi** [comment]
I aim to detect users' drag operations, but I'm unsure whether this plugin is the right solution for my needs.

**Comment by fonsp** [comment]
I see! And what is the drag interaction that you want to detect?

**Comment by guo-yong-zhi** [comment]
Actually, I want to drag and reposition the elements within the background SVG image. So some API like `update_background!(picker, new_svg_img)` is also needed. Is that possible?

API wanted: detect users' drag event, update background image
user function I already have: generate a new background image with the the drag event `(x_0, y_0, x_1, y_1)` 

For the plugin, it is also adequate to only report mouseup and mousedown events, rather than directly reporting drag events (the user can then calculate the drag actions based on these).

**Comment by fonsp** [comment]
Hey @guo-yong-zhi !

Thanks for the description! I don't think that this will be possible with PlutoImageCoordinatePicker.jl, but it should be possible with JavaScript in Pluto. Take a look at some of the docs pages on https://plutojl.org/en/docs/ like https://plutojl.org/en/docs/advanced-widgets/ .

Having input (drag events) and output (changing image) in the same cell is non-trivial in Pluto. It is possible using some tricks, e.g. take a look at how I implemented the initial interaction in https://computationalthinking.mit.edu/Fall24/climate_science/inverse_climate_model/

**Comment by fonsp** [comment]
I'll close this for now, but someone else has a good application for including the event type, then please leave a comment!
